CREATE TABLE "CAS_SERVICE"
(
    "ID" VARCHAR(255) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "EVALUATION_ORDER" INT,
    "LOGOUT_TYPE" INT,
    "LOGOUT_URL" VARCHAR(255),
    "NAME" VARCHAR(255),
    "SERVICEID" VARCHAR(255),
    "STATUS" CHAR(1) DEFAULT '1',
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "CAS_SERVICE" IS '单点登录服务信息';
COMMENT ON COLUMN "CAS_SERVICE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "CAS_SERVICE"."EVALUATION_ORDER" IS '排序';
COMMENT ON COLUMN "CAS_SERVICE"."ID" IS 'id';
COMMENT ON COLUMN "CAS_SERVICE"."LOGOUT_TYPE" IS '登出类型';
COMMENT ON COLUMN "CAS_SERVICE"."LOGOUT_URL" IS '登出URL';
COMMENT ON COLUMN "CAS_SERVICE"."NAME" IS '服务名称';
COMMENT ON COLUMN "CAS_SERVICE"."SERVICEID" IS '服务id';
COMMENT ON COLUMN "CAS_SERVICE"."STATUS" IS '(1 开启 0 关闭)';


CREATE UNIQUE  INDEX "INDEX1527722511239500" ON "CAS_SERVICE"("ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

insert into "CAS_SERVICE" ("ID","DESCRIPTION","EVALUATION_ORDER","LOGOUT_TYPE","LOGOUT_URL","NAME","SERVICEID","STATUS") values ('47', 'This service definition authorizes all application urls that support HTTPS and IMAPS protocols.', 10000, 0, null, 'HTTPS and IMAPS', '^(https|imaps|http)://.*', '1');
